# Generated by Django 4.2.3 on 2023-08-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='blog_post_attachments/'),
        ),
    ]
