# Generated by Django 4.2.3 on 2023-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_image_blogpost_file_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='file_attachment',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog_post_files/'),
        ),
    ]
